### ISSUE TITLE
'CaesarInterface' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

### ISSUE THREAD

**Issue by kolirt** [gitgud5/caesar-crypt#1]
Hey. Can you add a type to the import?

```
node_modules/caesar-crypt/index.ts:1:10 - error TS1484: 'CaesarInterface' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

1 import { CaesarInterface } from "./interface";
           ~~~~~~~~~~~~~~~


Found 1 error in node_modules/caesar-crypt/index.ts:1

```

**Comment by kolirt** [comment]
Like this
```ts
import type { CaesarInterface } from "./interface";
```

**Comment by gitgud5** [comment]
Hi @kolirt , thank you for opening the issue.
Would you like me to make a type for it specifically so that you can import that type?

**Comment by kolirt** [comment]
> Hi @kolirt , thank you for opening the issue. Would you like me to make a type for it specifically so that you can import that type?

I want you to add the word `type` after `import`. Here https://github.com/gitgud5/caesar-crypt/blob/master/index.ts#L1

**Comment by gitgud5** [comment]
Alright it is fixed now. You can check that out and let me know.

**Comment by kolirt** [comment]
> Alright it is fixed now. You can check that out and let me know.

thanks
